### PR TITLE
Update azure.functions.maven.plugin.version 1.0.0-beta-8-SNAPSHOT

### PR DESCRIPTION
**Pull request by pragnagopa**
Update E2E tests to use azure.functions.maven.plugin.version 1.0.0-beta-8-SNAPSHOT

### CODE REVIEW

**Comment by pragnagopa** [comment]
fyi @Flanker32

**Comment by pragnagopa** [comment]
@Flanker32 / @jdneo  - Can you please check pom.xml if I missed anything? Build is failing as it cannot find 
maven plugin version 1.0.0-beta-8-SNAPSHOT

**Comment by Flanker32** [comment]
> @Flanker32 / @jdneo - Can you please check pom.xml if I missed anything? Build is failing as it cannot find
> maven plugin version 1.0.0-beta-8-SNAPSHOT

@pragnagopa 
Please also set the `<pluginRepositories>` in the pom, you may refer to https://github.com/Microsoft/azure-maven-plugins/wiki/Test-Plan-for-Function the regression test part

**Comment by pragnagopa** [comment]
Thanks @Flanker32 . Let me know once you have a new snapshot version. I will update this PR. So far CosmosDB tests are failing due to https://github.com/Microsoft/azure-maven-plugins/issues/466

**Pull request merged**
