### PR TITLE
fix function name issue

### PR DESCRIPTION
**Pull request by kaibocai**
Fix the issue that function cannot have same method name as any other method in it's parent class.

### CODE REVIEW

**Review by TsuyoshiUshio — COMMENTED** [review]
Thank you for finding out this issue. 
For the change, Looks good to me. However, The CI fails by the other reason. Could you find the reason why it fails? 
Once CI has passed, I'd happy to approve this change.

**Comment by kaibocai** [comment]
> Thank you for finding out this issue.
> For the change, Looks good to me. However, The CI fails by the other reason. Could you find the reason why it fails?
> Once CI has passed, I'd happy to approve this change.

Hi @TsuyoshiUshio, yes currently trying to identify the reason and will get it resolved. Thanks.

**Pull request closed without merging**
