### PR TITLE
Minor changes to make it work on Java 11

### PR DESCRIPTION
**Pull request by mnriem**
Let me know if you need anything else.

Note I only tested it locally by patching the Java Worker JAR and validating that I could see it use Java 11 and then execute a function.

Thanks!

### CODE REVIEW

**Comment by helayoty** [comment]
lgtm by testing it locally as well

**Comment by jabrena** [comment]
Hi @helayoty,

Any progress ?

**Comment by amamounelsayed** [comment]
Thank you so much @helayoty and @mnriem. We will keep you update.

**Comment by amamounelsayed** [comment]
Thank you so much @mnriem and @helayoty . We put in considerations the changes for PR https://github.com/Azure/azure-functions-java-worker/pull/361

**Pull request closed without merging**
