### PR TITLE
Adding support for updated command line args

### LINKED ISSUE #724: Update java language worker to support handling new command line arguments with functions- prefix
The command-line arguments that the language worker receives from the Functions Host have generic names (such as 'host' and 'port'). This can cause conflicts with other environment variables in certain environments. To address this issue, the Functions Host will now send a new set of arguments prefixed with `functions-<argumentname>`. This will be in addition to the existing arguments.

With the new planned host change, host code will send command line arguments like below. 

> -host 127.0.0.1 --port 50821 --workerId e9efd817-47a1-45dc-9e20-e6f975d7a025 --requestId cbef5957-cdb3-4462-9ee7-ac9f91be0a51 --grpcMaxMessageLength 2147483647 --functions-uri http://127.0.0.1:50821 --functions-workerid e9efd817-47a1-45dc-9e20-e6f975d7a025 --functions-requestid cbef5957-cdb3-4462-9ee7-ac9f91be0a51 --functions-grpcmaxmessagelength 2147483647

The new arguments sent are: 

1. --functions-uri
2. --functions-worker-id
3. --functions-request-id
4. --functions-grpc-max-message-length

Initial sanity testing showed that python worker fails to start when the new arguments are sent. We need to fix the python worker to handle these new arguments.

#### Expected behavior with the fix:

1. Use the new arguments (the one with "functions-" prefix).
2. If the new arguments are not present, use the old ones (PORT, HOST etc..)

See https://github.com/Azure/azure-functions-host/issues/9504 for more details.

### PR DESCRIPTION
**Pull request by shreyas-gopalakrishna**
### handling new command line arguments with functions- prefix

resolves #724

Host issue https://github.com/Azure/azure-functions-host/issues/9504

### Pull request checklist

* [ ] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [ ] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by kaibocai — APPROVED** [review]
LGTM!

**Review by kamperiadis — APPROVED** [review]

**Comment by kaibocai** [comment]
Currently this will cause all the pipelines to fail, do we know when the latest host will be included in the pipeline core tools?

**Comment by shreyas-gopalakrishna** [comment]
All languages are updating the command line args and host team is doing a release once this is done. 
@kshyju can provide timelines

**Comment by kshyju** [comment]
> All languages are updating the command line args and host team is doing a release once this is done. @kshyju can provide timelines

The plan is to release the host changes along with the worker update in the same release.

**Pull request merged**
